language: php

php:
    - 8.1
    - 8.2
    - 8.3
    - nightly

env:
    - SYMFONY_VERSION=5.4.* # LTS
    - SYMFONY_VERSION=6.0.* # EOL
    - SYMFONY_VERSION=6.1.* # EOL
    - SYMFONY_VERSION=6.2.* # EOL
    - SYMFONY_VERSION=6.3.* # EOL
    - SYMFONY_VERSION=6.4.* # LTS
    - SYMFONY_VERSION=dev-master

global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - composer self-update
    - sh -c "if [ '$DEPENDENCIES' == 'dev' ]; then sed -i 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi"
    - sh -c "if [ '$SYMFONY_VERSION' != '' ]; then composer require symfony/symfony:${SYMFONY_VERSION}; fi"

install: composer install

script:
    - ant test

matrix:
    allow_failures:
        - env: SYMFONY_VERSION=dev-master
        - php: nightly